name: QA URL Scan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mock repo (PR branch only)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout QA automation
        uses: actions/checkout@v4
        with:
          repository: Seyminie/qa-automation
          path: scanner
          token: ${{ secrets.QA_AUTOMATION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run QA URL Scanner
        working-directory: scanner
        run: python scanner/main.py ../ || exit 1

