name: QA URL Scan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read   # required to read another repo

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout website repo (PR code)
        uses: actions/checkout@v4

      - name: Checkout scanner repo
        uses: actions/checkout@v4
        with:
          repository: Seyminie/qa-automation
          path: scanner
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scanner/requirements.txt

      - name: Run QA URL Scanner
        run: python scanner/main.py ./
