jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout website repo
        uses: actions/checkout

      - name: Checkout scanner repo
        uses: actions/checkout
        with:
          repository: Seyminie/qa-automation
          path: scanner

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r scanner/requirements.txt

      - name: Run QA URL Scanner
        run: python scanner/main.py ./
